### ISSUE TITLE
About the concept of optimization

### ISSUE THREAD

**Issue by tszslovewanpu** [deqiankong/SGDS#1]
Hello, and fantastic work! I have a question regarding the optimization concept.

In the context of 
SINGLE-OBJECTIVE OPTIMIZATION、MULTI-OBJECTIVE OPTIMIZATION、CONSTRAINED OPTIMIZATION, etc.
what is the target of optimization?

Is it the latent variable 'z,' or is it the prediction model 'pγ'?

I understand this might be a bit of a basic question, but I'm hoping you can help clarify this concept for me. Thank you so much! ^v^

**Comment by deqiankong** [comment]
Hello,

Thank you for your interest!

In single-objective optimization, our goal is to identify a molecule (denoted as $x$) that maximizes a specific property value ($y$). In multi-objective benchmarks, we aim to discover $x$ that simultaneously maximizes multiple values ($y_1, y_2, ..., y_n$). This process involves initially sampling $z$ from $p(z|y)$, followed by generating $x$ from $p(x|z)$ in a sequential manner.

I hope this explanation resolves any confusion.
